name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  typecheck:
    name: TypeCheck
    uses: ./.github/workflows/typecheck.yml

  build:
    name: Build
    needs: [lint, typecheck]
    uses: ./.github/workflows/build.yml
